version: "3.5"
services:

  mysql:
    image: mysql:8.0.20
    container_name: test_mysql
    command:
      --default-authentication-plugin=mysql_native_password
    expose:
      - 3306
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Pa55w0rd

volumes:
  mysql_data:
    external: false    
      
